blog/urls.py
from django.urls import path

from blog import views

app_name = "blog"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:post_id>/', views.single_post, name="single-post"),
]

learning_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_not_required
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from learning_django import views

admin.site.site_header = "learning_django admin site"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('health_check', views.healthcheck, name='healthcheck'),
    path('api-token-auth/', login_not_required(TokenObtainPairView.as_view()), name='api-token-obtain-pair'),
    path('api-token-refresh/', login_not_required(TokenRefreshView.as_view()), name='api-token-refresh'),
]

configuration_name = settings.CONFIGURATION.split(".")[-1]

if configuration_name == "Development":
    urlpatterns.extend([path('api/schema/', login_not_required(SpectacularAPIView.as_view()), name='schema'),
                        # Optional UI:
                        path('api/schema/swagger-ui/', login_not_required(SpectacularSwaggerView.as_view(url_name='schema')),
                             name='swagger-ui'),
                        path('api/schema/redoc/', login_not_required(SpectacularRedocView.as_view(url_name='schema')), name='redoc')])

    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Author(models.Model):
    first_name = models.CharField(verbose_name="שם", blank=False, null=False)
    surname = models.CharField(verbose_name="משפחה", blank=False, null=False)
    email = models.EmailField(verbose_name="דואר אלקטרוני", blank=True, null=True)
    phone = models.CharField(verbose_name="טלפון", blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.surname}"


class Post(models.Model):
    title = models.CharField(verbose_name="כותרת", blank=False, null=False)
    content = models.TextField(verbose_name="תוכן", blank=False, null=False)
    updated_at = models.DateTimeField(verbose_name="עדכון אחרון", blank=False, null=False)
    author = models.ForeignKey(to=Author, on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render

from blog.models import Post, Author


def index(request):
     authors = Author.objects.all()
     posts = Post.objects.all()
     query_params = request.GET
     author_id = query_params.get("author_id")
     if author_id:
          posts = posts.filter(author_id=author_id)
     context = {"posts": posts, "authors": authors}
     return render(request, "blog/index.html", context)


def single_post(request, post_id):
     post = Post.objects.get(pk=post_id)
     context = {"post": post}
     return render(request, "blog/single-post.html", context)

learning_django/views.py
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_not_required

@login_not_required
def healthcheck(request):
    return JsonResponse({"status": "OK"})

blog/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <title>הבלוג שלנו</title>
</head>
<body dir="rtl">
<main>
    <h1>הבלוג שלנו</h1>

    <div class="authors">
        <p>
            {% for author in authors %}
                <a href="{% url 'blog:index'%}{% querystring author_id=author.id %}" class="author-link">{{ author}}</a>
            {% endfor %}
            <a href="{% url 'blog:index'%}" class="author-link">כולם</a>
        </p>
    </div>

    {% for post in posts %}
    <div class="post-item">
        <h2>{{ post.title }} - {{ post.author }}</h2>
        <p>{{ post.content }}</p>
        <p><i>{{ post.updated_at }}</i></p>
        <a href="{% url 'blog:single-post' post.id %}">קישור</a>

    </div>
    {% endfor %}

</main>
</body>
</html>

blog/templates/blog/single-post.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <title>הבלוג שלנו</title>
</head>
<body dir="rtl">
<main>
    <h1>{{ post.title }} - {{ post.author }}</h1>
    <div class="post-item">
        <p>{{ post.content }}</p>
        <p><i>{{ post.updated_at }}</i></p>
    </div>
    <a href="{% url 'blog:index' %}">לרשימת הפוסטים</a>
</main>
</body>
</html>